### PR TITLE
feature: PrimeNG refactor Organization Form Component

### PR DESCRIPTION
**Pull request by NOPROD**
# Pull Request

Thank you for your contribution to the Bulwark. Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] A new feature
- [ ] A bug fix
- [ ] Documentation only changes
- [ ] Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- [X] A code change that neither fixes a bug nor adds a feature
- [ ] A code change that improves performance
- [ ] Adding missing tests or correcting existing tests
- [ ] Changes that affect the build system or external dependencies
- [ ] Changes to our CI configuration files and scripts
- [ ] Other changes that don't modify src or test files

Add description here

``` release-note
Refactor org-form.component.html to use PrimeNG's form components

```

---

## Checklist

- [X] My code follows the [contributing](../CONTRIBUTING.md) guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by NOPROD** [comment]
Old layout : 

Mobile
org-form-mobile-oroginal

Desktop
org-form-original-desktop

Tablet
org-form-tablet-original

**Comment by NOPROD** [comment]
New layout

Mobile
org-new-mobile

Desktop
org-new-desk


Tablet don't change ^^

**Comment by NOPROD** [comment]
You need a custom theme file i think. To make change with PrimeNg  more easier



I think it's more clean to change PrismeNg default variable rather than use class like
`
btn-primary.p-button:active
btn-primary.p-button:hover
btn-primary.p-button
...
`

to see during the next pr ...

Let's already try to pass a pr with the minimum ^^

**Comment by Whamo12** [comment]
> You need a custom theme file i think. To make change with PrimeNg more easier
> 
> I think it's more clean to change PrismeNg default variable rather than use class like
> `btn-primary.p-button:active btn-primary.p-button:hover btn-primary.p-button ...`
> 
> to see during the next pr ...
> 
> Let's already try to pass a pr with the minimum ^^

I agree.  We started this project using Bootstrap which is why you're seeing this.

**Comment by Whamo12** [comment]
@NOPROD The update to the `styles.scss` removes the current primary styling from every other button in the application.  Is there a way to have the refactored PrimeNG styling work with the current styling?

Screen Shot 2020-10-21 at 9 13 34 AM

**Comment by NOPROD** [comment]
@Whamo12  Wouuups, Sorry, :/  it's updated

**Review by Whamo12 — APPROVED** [review]

**Pull request merged**
