### PR TITLE
Asset Archive Feature

### LINKED ISSUE #167: Archive - Assets
As a user, I should be able to archive an asset so that it will no longer show up as an active asset.  Once an asset is updated to be archived, it will be moved to an Archive view where all archive assets will be viewable.  Once an asset is archived, assessments can no longer be associated to it.

### PR DESCRIPTION
**Pull request by Whamo12**
# Pull Request

Fixes #167 

## Type of change

- [x] A new feature
- [ ] A bug fix
- [ ] Documentation only changes
- [ ] Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- [ ] A code change that neither fixes a bug nor adds a feature
- [ ] A code change that improves performance
- [ ] Adding missing tests or correcting existing tests
- [ ] Changes that affect the build system or external dependencies
- [ ] Changes to our CI configuration files and scripts
- [ ] Other changes that don't modify src or test files

This pull request allows the user to archive assets so that it can be removed from active assets.

---

## Checklist

- [x] My code follows the [contributing](../CONTRIBUTING.md) guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Whamo12** [comment]
@DarrellRichards With this pull-request, I have managed to stabilize the unit test infrastructure with Sqlite3.  I have added dynamic column options so that that databases are isolated.  I have also introduced the node env `test` which jest will only use.  Please review the test within this PR if you're free.  Thanks!

**Comment by DarrellRichards** [comment]
@Whamo12 

This LGTM 🚀 🎸

I like the usage of the sqlite3 and mock-express's `request` & `responses` instead of the customs ones we started out with.

I ran the test and seeing about `52%` line coverage on `asset.controller.ts`, everything was passing.

**Comment by Whamo12** [comment]
> I ran the test and seeing about `52%` line coverage on `asset.controller.ts`, everything was passing. 

We have an existing issue for the asset controller and the remainder of the tests will be finished there.

Thanks for the review.  A lot of unknowns in regard to the backend unit tests were resolved here which makes me happy.

**Comment by DarrellRichards** [comment]
> 
> 
> > I ran the test and seeing about `52%` line coverage on `asset.controller.ts`, everything was passing. 
> 
> We have an existing issue for the asset controller and the remainder of the tests will be finished there.
> 
> Thanks for the review.  A lot of unknowns in regard to the backend unit tests were resolved here which makes me happy.
> 
> 

Understood, just wanted to make sure I wasn't missing something. 

I'm glad everything is coming together so nicely.

Hopefully, I'll have some time upcoming to help the unit testing integration.

**Pull request merged**
