### PR TITLE
Adding Backend tests support to CI

### LINKED ISSUE #267: Add backend unit test to github action
While our backend unit tests are incomplete, enough are completed to add benefit to the pull request build.

### PR DESCRIPTION
**Pull request by DarrellRichards**
# Pull Request

Added support to the CI to support running the backend tests.

Fixes #267 

## Type of change

- [x] A new feature
- [ ] A bug fix
- [ ] Documentation only changes
- [ ] Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- [ ] A code change that neither fixes a bug nor adds a feature
- [ ] A code change that improves performance
- [ ] Adding missing tests or correcting existing tests
- [ ] Changes that affect the build system or external dependencies
- [x] Changes to our CI configuration files and scripts
- [ ] Other changes that don't modify src or test files

```release-note
Added support for backend tests to run in the CI

```

---

## Checklist

- [x] My code follows the [contributing](../CONTRIBUTING.md) guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by DarrellRichards** [comment]
@Whamo12 Wasn't sure if you would like, but we can also add support to the CI to only run these tests on a PR and Push to master only if the backend code is touched.

**Comment by Whamo12** [comment]
@DarrellRichards As long as it does not interfere with the current build process when Dependabot opens a PR, that would be a good enhancement.  Dependabot runs a scan against both the backend and frontend package.json files and will open a PR with any update.

**Comment by DarrellRichards** [comment]
> @DarrellRichards As long as it does not interfere with the current build process when Dependabot opens a PR, that would be a good enhancement. Dependabot runs a scan against both the backend and frontend package.json files and will open a PR with any update.

With the above approach, this will affect Dependabot runs or PR's. It's set to check for any files changed in the `/src` folder

**Comment by Whamo12** [comment]
@DarrellRichards I'm running [ACT](https://github.com/nektos/act) to test this Github action locally and I am getting the following error:
```
Alejandros-MBP:bulwark alejandrosaenz$ act
[build/build-3] 🧪  Matrix: map[node-version:14.x]
[build/build-3] 🚀  Start image=node:12.6-buster-slim
[build/build-2] 🧪  Matrix: map[node-version:12.x]
[build/build-2] 🚀  Start image=node:12.6-buster-slim
[build/build-1] 🧪  Matrix: map[node-version:10.x]
[build/build-1] 🚀  Start image=node:12.6-buster-slim
[build/build-1]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[build/build-2]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[build/build-1]   🐳  docker cp src=/Users/alejandrosaenz/Repositories/bulwark-contrib/darrell/bulwark/. dst=/github/workspace
[build/build-2]   🐳  docker cp src=/Users/alejandrosaenz/Repositories/bulwark-contrib/darrell/bulwark/. dst=/github/workspace
[build/build-2] ⭐  Run actions/checkout@v2
[build/build-2]   ✅  Success - actions/checkout@v2
ERRO[0007] Unable to interpolate string '${{ matrix.node-version }}' - [ReferenceError: 'version' is not defined] 
[build/build-2] ⭐  Run Use Node.js ${{ matrix.node-version }}
[build/build-2]   ☁  git clone 'https://github.com/actions/setup-node' # ref=v1
[build/build-1] ⭐  Run actions/checkout@v2
[build/build-1]   ✅  Success - actions/checkout@v2
ERRO[0007] Unable to interpolate string '${{ matrix.node-version }}' - [ReferenceError: 'version' is not defined] 
[build/build-1] ⭐  Run Use Node.js ${{ matrix.node-version }}
[build/build-1]   ☁  git clone 'https://github.com/actions/setup-node' # ref=v1
[build/build-2]   🐳  docker cp src=/Users/alejandrosaenz/.cache/act/actions-setup-node@v1 dst=/actions/
[build/build-1]   🐳  docker cp src=/Users/alejandrosaenz/.cache/act/actions-setup-node@v1 dst=/actions/
| [command]/usr/local/bin/node --version
| v12.6.0
| [command]/usr/local/bin/npm --version
| [command]/usr/local/bin/node --version
| v12.6.0
| [command]/usr/local/bin/npm --version
| 6.9.0
| 6.9.0
[build/build-2]   ❓  ##[add-matcher]/actions/actions-setup-node@v1/.github/tsc.json
[build/build-2]   ❓  ##[add-matcher]/actions/actions-setup-node@v1/.github/eslint-stylish.json
[build/build-2]   ❓  ##[add-matcher]/actions/actions-setup-node@v1/.github/eslint-compact.json
[build/build-1]   ❓  ##[add-matcher]/actions/actions-setup-node@v1/.github/tsc.json
[build/build-1]   ❓  ##[add-matcher]/actions/actions-setup-node@v1/.github/eslint-stylish.json
[build/build-1]   ❓  ##[add-matcher]/actions/actions-setup-node@v1/.github/eslint-compact.json
[build/build-2]   ✅  Success - Use Node.js ${{ matrix.node-version }}
[build/build-2] ⭐  Run dorny/paths-filter@v2.2.0
[build/build-2]   ☁  git clone 'https://github.com/dorny/paths-filter' # ref=v2.2.0
[build/build-1]   ✅  Success - Use Node.js ${{ matrix.node-version }}
[build/build-1] ⭐  Run dorny/paths-filter@v2.2.0
[build/build-1]   ☁  git clone 'https://github.com/dorny/paths-filter' # ref=v2.2.0
[build/build-2]   🐳  docker cp src=/Users/alejandrosaenz/.cache/act/dorny-paths-filter@v2.2.0 dst=/actions/
[build/build-1]   🐳  docker cp src=/Users/alejandrosaenz/.cache/act/dorny-paths-filter@v2.2.0 dst=/actions/
| /actions/dorny-paths-filter@v2.2.0/dist/index.js:21219
|         
|         
| 
| SyntaxError: Unexpected end of input
|     at Module._compile (internal/modules/cjs/loader.js:720:23)
|     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
|     at Module.load (internal/modules/cjs/loader.js:643:32)
|     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
|     at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
|     at internal/main/run_main_module.js:17:11
[build/build-2]   ❌  Failure - dorny/paths-filter@v2.2.0
Error: exit with `FAILURE`: 1
```

I ran this without any updates to the backend code.

**Comment by DarrellRichards** [comment]
@Whamo12 
I'll take look into, I see that running with act it runs an issue with how `dorny/path-filter` runs a `git fetch --depth` to see the file changes in all commits.

**Comment by DarrellRichards** [comment]
@Whamo12 

After looking into the issue deeper, it seems as if ACT has an issue with checking the authenticity of the git host. 

I also tried `act -P ubuntu-latest=nektos/act-environments-ubuntu:18.04` which gives full access to git and still the same issue.

The way Path Filter works: it fetches via the ref in my case because of the branch it fetches remote for the branch of `ci/backend-support` this is currently failing within the ACT docker because of the lack of `known_hosts`

Github Issue Reference: https://github.com/nektos/act/issues/191

With all of that being said, I can try and find a different approach however, I feel the issue we're facing is caused but the issue above.

**Review by Whamo12 — COMMENTED** [review]
I have tested this locally and it runs fine.  However, I'm going to merge this after #266 since that PR has conditionals to not send emails when running the backend unit tests.

**Review by Whamo12 — APPROVED** [review]

**Pull request merged**
